### ISSUE TITLE
Calc others button doesn't work

### ISSUE THREAD

**Issue by spuder** [apocolipse/RotorPirates#3]
Error console shows connection refused

<img width="1365" alt="screenshot 2018-04-10 07 44 41" src="https://user-images.githubusercontent.com/242382/38560552-20ab348c-3c93-11e8-8563-7078cc49ffd8.png">

**Comment by apocolipse** [comment]
@spuder conversion is API powered and nginx gets bogged down some times (its running on an AWS t1.micro instance so), feel free to ping me on slack/discord/where ever if its down so I can restart it
