### ISSUE TITLE
Calc is not working

### ISSUE THREAD

**Issue by DroidmanFPV** [apocolipse/RotorPirates#5]
I'm using Chrome and trying to use the calculator but it's not working.

**Comment by morlandi-jss** [comment]
seems that https://api.apocolipse.com/rates is not reachable

**Comment by apocolipse** [comment]
Conversion is API powered and nginx gets bogged down some times (its running on an AWS t1.micro instance so), feel free to ping me on slack/discord/where ever if its down so I can restart it
