### ISSUE TITLE
Raceflight One rates

### ISSUE THREAD

**Issue by spuder** [apocolipse/RotorPirates#6]
flight one (not the same as raceflight, or raceflight one) has the ability to share rates online as json. For example, here are captian vanovers rates

https://flightone.com/tuneconfigs/json/9317

It would be nice to be able to take these rates and convert them to betaflight.

**Comment by apocolipse** [comment]
@spuder just input the rates into RaceFlight rates.  FlightOne is just RaceFlightOne, its rate system is the same, the ability to "share" via json is irrelevant.
